<a href="https://colab.research.google.com/github/jxlyn/CSCI-4962-Projects-ML-AI/blob/main/Homework2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

I slightly modified my machine learning problem from homework 1 to make my result more accurate. The accuracy in my homework 1 is only 0.01 since we need to find a winner from 500 players which is 1/500. I changed my problem from predict whether or not a person will win a wrestling game to predict whether or not a person will be rank first 10 in a wrestling game. 


 **Task 1 (30 points): Implement a Decision Tree Classifier for your classification problem. You
may use a built-in package to implement your classifier. Try modifying one or more of the input
parameters and describe what changes you notice in your results. Clearly describe how these
factors are affecting your output.**

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import warnings
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score
from google.colab import drive
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from numpy import mean
from numpy import std
from sklearn.model_selection import KFold
from sklearn.model_selection import RepeatedStratifiedKFold
warnings.filterwarnings("ignore")

def accuracy(X,y,model):
  #use the formula from the lecture
  # repeated k-fold process
  cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
  n_scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
  # report performance
  print('Accuracy: %.3f, standard deviation is %.3f' % (mean(n_scores), std(n_scores)))
 
drive.mount('/content/drive')
data = pd.read_csv('drive/My Drive/ML and AI/Hw1/data.csv')

new_data2 = data.copy()
X = new_data2.drop(["gender", "nationality", "federation","name","sports","Unnamed: 0"], axis=1)
X = X.to_numpy()

Y = new_data2.drop(["gender", "nationality", "federation","name","sports","Unnamed: 0"], axis=1)
Y = Y.pop("rank").values

# if the rank is first 100, set it to 1(yes)
# if not, set it to 0 (no)
for z in range(len(Y)):
  if Y[z] <= 10:
    Y[z] =1
  else:
    Y[z] =0



Mounted at /content/drive


In [96]:
model = DecisionTreeClassifier(max_depth=100, min_samples_split = 2, max_features =3)
model = model.fit(X, Y)
print("Decision tree classifier before modifying: ")
accuracy(X,Y,model)

Decision tree classifier before modifying: 
Accuracy: 0.993, standard deviation is 0.011


As we can see the accuracy for decision tree classifier before modifying is very low.

In [88]:
## modifying the depth 
more_depth_model = DecisionTreeClassifier(max_depth =999,min_samples_split = 2, max_features =3).fit(X,Y)
print("The accuracy for decision tree classifier with more depth:")
accuracy(X,Y,more_depth_model)

less_depth_model = DecisionTreeClassifier(max_depth =1,min_samples_split = 2, max_features =3).fit(X,Y)
print("\nThe accuracy for decision tree classifier with less depth:")
accuracy(X,Y,less_depth_model)

The accuracy for decision tree classifier with more depth:
Accuracy: 0.994, standard deviation is 0.012

The accuracy for decision tree classifier with less depth:
Accuracy: 0.988, standard deviation is 0.010


As we can see,if we increase the max_depth and keep other factors constant, the accuracy will increase. If we decrease the max_depth and keep other factors constant, the accuracy will decrease.

In [98]:
## modifying the min_samples_split 
more_sample_model = DecisionTreeClassifier(max_depth =100,min_samples_split = 4, max_features =3).fit(X,Y)
print("The accuracy for decision tree classifier with more min_samples_split:")
accuracy(X,Y,more_sample_model)

less_sample_model = DecisionTreeClassifier(max_depth =100,min_samples_split = 0.1, max_features =3).fit(X,Y)
print("\nThe accuracy for decision tree classifier with less min_samples_split:")
accuracy(X,Y,less_sample_model)

The accuracy for decision tree classifier with more min_samples_split:
Accuracy: 0.995, standard deviation is 0.010

The accuracy for decision tree classifier with less min_samples_split:
Accuracy: 0.991, standard deviation is 0.011


As we can see as the min_samples_split increases, the accuracy increases. As the min_samples_split decreases, the accuracy decreases.

In [73]:
## modifying the max_features
more_feature_model = DecisionTreeClassifier(max_depth =100,min_samples_split = 2, max_features =5).fit(X,Y)
print("The accuracy for decision tree classifier with more max_features:")
accuracy(X,Y,more_feature_model)

less_feature_model = DecisionTreeClassifier(max_depth =100,min_samples_split = 2, max_features =1).fit(X,Y)
print("\nThe accuracy for decision tree classifier with less max_features:")
accuracy(X,Y,less_feature_model)

The accuracy for decision tree classifier with more max_features:
Accuracy: 0.997, standard deviation is 0.007

The accuracy for decision tree classifier with less max_features:
Accuracy: 0.983, standard deviation is 0.016


As we can see as the max_feature increases, the accuracy increases. As the max_feature decreases, the accuracy decreases.

**Task 2 (30 points): From the Bagging and Boosting ensemble methods pick any one algorithm
from each category. Implement both the algorithms using the same data. Use k-fold cross
validation to find the effectiveness of both the models. Comment on the difference/similarity of
the results.**

In [100]:

#Implementing Random Forest
RF_model = RandomForestClassifier(max_depth=100, min_samples_split = 2, max_features =3).fit(X,Y)
print("The accuracy for random forest model:")
accuracy(X,Y,RF_model)

#Implementing Adaboost
Adaboost_model = AdaBoostClassifier(n_estimators=4, random_state=0, algorithm='SAMME')
print("\nThe accuracy for Adaboost model:")
accuracy(X,Y,Adaboost_model)


The accuracy for random forest model:
Accuracy: 0.997, standard deviation is 0.007

The accuracy for Adaboost model:
Accuracy: 0.999, standard deviation is 0.005


As we can see the difference between the random forest model and adaboost model is that adaboost model have higher accuracy and smaller standard deviation than random forest model. The similarity between the random forest model and adaboost model is they both are more accurate than decision tree model.

**Task 3 (40 points): Compare the effectiveness of the three models implemented above. Clearly
describe the metric you are using for comparison. Describe (with examples) Why is this
metric(metrics) suited/appropriate for the problem at hand? How would a choice of a different
metric impact your results? Can you demonstrate that?**

In [23]:
train_X , test_X, train_Y, test_Y = train_test_split(X,Y,train_size =0.6,test_size=0.4,random_state =0)
tree_model = DecisionTreeClassifier(max_depth=100, min_samples_split = 2, max_features =3).fit(train_X,train_Y)
pred_y1 = tree_model.predict(test_X)
print(f"Confusion matrix for decision tree model: \n{confusion_matrix(test_Y, pred_y1)}")
print(f"Accuracy score for decision tree model: {accuracy_score(pred_y1, test_Y)}")
print(f"F1 score for decision tree model: {f1_score( test_Y,pred_y1,average='weighted')}")

RF_model2 = RandomForestClassifier(max_depth=100, min_samples_split = 2, max_features =3).fit(train_X,train_Y)
pred_y2 = RF_model2.predict(test_X)
print(f"\nConfusion matrix for random forest model: \n{confusion_matrix(test_Y, pred_y2)}")
print(f"Accuracy score for random forest model: {accuracy_score(pred_y2, test_Y)}")
print(f"F1 score for random forest model: {f1_score( test_Y,pred_y2,average='weighted')}")

Adaboost_model2 = AdaBoostClassifier(n_estimators=4, random_state=0, algorithm='SAMME').fit(train_X,train_Y)
pred_y3 = Adaboost_model2.predict(test_X)
print(f"\nConfusion matrix for adaboost model: \n{confusion_matrix(test_Y, pred_y3)}")
print(f"Accuracy score for adaboost model: {accuracy_score(pred_y3, test_Y)}")
print(f"F1 score for adaboost model: {f1_score( test_Y,pred_y3,average='weighted') }")



Confusion matrix for decision tree model: 
[[191   3]
 [  4   2]]
Accuracy score for decision tree model: 0.965
F1 score for decision tree model: 0.9634540780556204

Confusion matrix for random forest model: 
[[194   0]
 [  4   2]]
Accuracy score for random forest model: 0.98
F1 score for random forest model: 0.9751020408163267

Confusion matrix for adaboost model: 
[[194   0]
 [  2   4]]
Accuracy score for adaboost model: 0.99
F1 score for adaboost model: 0.989025641025641


As we can see among decision tree model, adaboost model, random forest model, the most accurate one is adaboost model. It has the highest accuracy and F1 score. I used confusion matrix, accuracy score, F1 score as the metic for comparison. I also used the same metric in homework 1. This is a suitable metric for predicting who will rank top 10 in a wrestling game because when predicting whether or not a person will be the top 10 players in a wrestling game, we need to consider the accuracy for each model, and F1 score. The result will be significantly affected if we pick the model with low accuracy score and F1 score. The F1 score indicates precision and recall of a classifier. If model's F1 score is closer to 1, we can conclude that the model is more accurate. When predicting who'll be the top 10 players in the wrestling game, the accuracy is extremely important, if will make player lose confidence, or being over-cofident. Also, there are people who will bet on who will win the wrestling game. By predicting the top 10 players in a wrestling game, it can help them eliminate some choices. If the prediction is inaccurate, people will lose money.